// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#ifndef _CARUI_UI_H
#define _CARUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_LockScreen
void ui_LockScreen_screen_init(void);
void ui_event_LockScreen(lv_event_t * e);
extern lv_obj_t * ui_LockScreen;
extern lv_obj_t * ui_logoImage;
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_BatteryPercentLabel;
extern lv_obj_t * ui_BatteryPercentBar;
extern lv_obj_t * ui_BatteryTempLabel;
extern lv_obj_t * ui_BatteryTempBar;
extern lv_obj_t * ui_PowerArc;
extern lv_obj_t * ui_RecuArc;
extern lv_obj_t * ui_BatteryArc;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_kmhLabel;
extern lv_obj_t * ui_StatePanel;
extern lv_obj_t * ui_StateLabel;
extern lv_obj_t * ui_ShutdownPanel;
extern lv_obj_t * ui_ShutdownLabel;
extern lv_obj_t * ui_BrakeBar;
extern lv_obj_t * ui_GasBar;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_PowermodeLabel;
// SCREEN: ui_BatteryScreen
void ui_BatteryScreen_screen_init(void);
void ui_event_BatteryScreen(lv_event_t * e);
extern lv_obj_t * ui_BatteryScreen;
extern lv_obj_t * ui_CellVoltagePanel;
extern lv_obj_t * ui_MaxCellVoltageLabel;
extern lv_obj_t * ui_MinCellTempPanel;
extern lv_obj_t * ui_MaxCellTempLabel;
extern lv_obj_t * ui_MaxCellLabel;
extern lv_obj_t * ui_MaxCellVoltagePanel;
extern lv_obj_t * ui_MinCellVoltageLabel;
extern lv_obj_t * ui_MaxCellTempPanel;
extern lv_obj_t * ui_MinCellTempLabel;
extern lv_obj_t * ui_MinCellLabel;
extern lv_obj_t * ui_BatteryPercentBar1;
extern lv_obj_t * ui_BatteryVoltageLabel;
extern lv_obj_t * ui_BatteryPercentLabel1;
extern lv_obj_t * ui_BatteryVoltageBar;
// SCREEN: ui_MotorScreen
void ui_MotorScreen_screen_init(void);
void ui_event_MotorScreen(lv_event_t * e);
extern lv_obj_t * ui_MotorScreen;
extern lv_obj_t * ui_MotorTempBar;
extern lv_obj_t * ui_MotorTempLabel;
extern lv_obj_t * ui_AirTempBar;
extern lv_obj_t * ui_AirTempLabel;
extern lv_obj_t * ui_kmhLabel1;
extern lv_obj_t * ui_SpeedLabel1;
extern lv_obj_t * ui_PowerArc1;
extern lv_obj_t * ui_RecuArc1;
extern lv_obj_t * ui_BatteryArc1;
extern lv_obj_t * ui_PowermodeLabel1;
// SCREEN: ui_DebugScreen
void ui_DebugScreen_screen_init(void);
void ui_event_DebugScreen(lv_event_t * e);
extern lv_obj_t * ui_DebugScreen;
extern lv_obj_t * ui_StatePanel1;
extern lv_obj_t * ui_StateLabel1;
extern lv_obj_t * ui_ShutdownPanel1;
extern lv_obj_t * ui_ShutdownLabel1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo_png);    // assets\logo.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
