// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#include "ui.h"

void changePowerMode(lv_event_t *e)
{
	// send a message to the CAN bus
}
