// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#include "../ui.h"

void ui_BatteryScreen_screen_init(void)
{
    ui_BatteryScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BatteryScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CellVoltagePanel = lv_obj_create(ui_BatteryScreen);
    lv_obj_set_width(ui_CellVoltagePanel, 70);
    lv_obj_set_height(ui_CellVoltagePanel, 70);
    lv_obj_set_x(ui_CellVoltagePanel, -170);
    lv_obj_set_y(ui_CellVoltagePanel, -40);
    lv_obj_set_align(ui_CellVoltagePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CellVoltagePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MaxCellVoltageLabel = lv_label_create(ui_CellVoltagePanel);
    lv_obj_set_width(ui_MaxCellVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxCellVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MaxCellVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxCellVoltageLabel, "3.5V");

    ui_MinCellTempPanel = lv_obj_create(ui_BatteryScreen);
    lv_obj_set_width(ui_MinCellTempPanel, 70);
    lv_obj_set_height(ui_MinCellTempPanel, 70);
    lv_obj_set_x(ui_MinCellTempPanel, -170);
    lv_obj_set_y(ui_MinCellTempPanel, 60);
    lv_obj_set_align(ui_MinCellTempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MinCellTempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MaxCellTempLabel = lv_label_create(ui_MinCellTempPanel);
    lv_obj_set_width(ui_MaxCellTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxCellTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MaxCellTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxCellTempLabel, "50°C");

    ui_MaxCellLabel = lv_label_create(ui_BatteryScreen);
    lv_obj_set_width(ui_MaxCellLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxCellLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxCellLabel, -170);
    lv_obj_set_y(ui_MaxCellLabel, -100);
    lv_obj_set_align(ui_MaxCellLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxCellLabel, "MAX");
    lv_obj_set_style_text_font(ui_MaxCellLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxCellVoltagePanel = lv_obj_create(ui_BatteryScreen);
    lv_obj_set_width(ui_MaxCellVoltagePanel, 70);
    lv_obj_set_height(ui_MaxCellVoltagePanel, 70);
    lv_obj_set_x(ui_MaxCellVoltagePanel, -65);
    lv_obj_set_y(ui_MaxCellVoltagePanel, -40);
    lv_obj_set_align(ui_MaxCellVoltagePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MaxCellVoltagePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinCellVoltageLabel = lv_label_create(ui_MaxCellVoltagePanel);
    lv_obj_set_width(ui_MinCellVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinCellVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MinCellVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinCellVoltageLabel, "3.5V");

    ui_MaxCellTempPanel = lv_obj_create(ui_BatteryScreen);
    lv_obj_set_width(ui_MaxCellTempPanel, 70);
    lv_obj_set_height(ui_MaxCellTempPanel, 70);
    lv_obj_set_x(ui_MaxCellTempPanel, -65);
    lv_obj_set_y(ui_MaxCellTempPanel, 60);
    lv_obj_set_align(ui_MaxCellTempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MaxCellTempPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinCellTempLabel = lv_label_create(ui_MaxCellTempPanel);
    lv_obj_set_width(ui_MinCellTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinCellTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MinCellTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinCellTempLabel, "50°C");

    ui_MinCellLabel = lv_label_create(ui_BatteryScreen);
    lv_obj_set_width(ui_MinCellLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinCellLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinCellLabel, -65);
    lv_obj_set_y(ui_MinCellLabel, -100);
    lv_obj_set_align(ui_MinCellLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinCellLabel, "MIN");
    lv_obj_set_style_text_font(ui_MinCellLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryPercentBar1 = lv_bar_create(ui_BatteryScreen);
    lv_bar_set_value(ui_BatteryPercentBar1, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryPercentBar1, 60);
    lv_obj_set_height(ui_BatteryPercentBar1, 170);
    lv_obj_set_x(ui_BatteryPercentBar1, 50);
    lv_obj_set_y(ui_BatteryPercentBar1, 10);
    lv_obj_set_align(ui_BatteryPercentBar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryPercentBar1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryPercentBar1, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryPercentBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryPercentBar1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryPercentBar1, lv_color_hex(0x3030F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryPercentBar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BatteryVoltageLabel = lv_label_create(ui_BatteryScreen);
    lv_obj_set_width(ui_BatteryVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryVoltageLabel, 150);
    lv_obj_set_y(ui_BatteryVoltageLabel, -100);
    lv_obj_set_align(ui_BatteryVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryVoltageLabel, "400V");
    lv_obj_set_style_text_font(ui_BatteryVoltageLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryPercentLabel1 = lv_label_create(ui_BatteryScreen);
    lv_obj_set_width(ui_BatteryPercentLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryPercentLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryPercentLabel1, 50);
    lv_obj_set_y(ui_BatteryPercentLabel1, -100);
    lv_obj_set_align(ui_BatteryPercentLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryPercentLabel1, "100%");
    lv_obj_set_style_text_font(ui_BatteryPercentLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryVoltageBar = lv_bar_create(ui_BatteryScreen);
    lv_bar_set_value(ui_BatteryVoltageBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryVoltageBar, 60);
    lv_obj_set_height(ui_BatteryVoltageBar, 170);
    lv_obj_set_x(ui_BatteryVoltageBar, 150);
    lv_obj_set_y(ui_BatteryVoltageBar, 10);
    lv_obj_set_align(ui_BatteryVoltageBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryVoltageBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryVoltageBar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryVoltageBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryVoltageBar, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryVoltageBar, lv_color_hex(0x3030F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryVoltageBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BatteryScreen, ui_event_BatteryScreen, LV_EVENT_ALL, NULL);

}
