// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#include "../ui.h"

void ui_DebugScreen_screen_init(void)
{
    ui_DebugScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DebugScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatePanel1 = lv_obj_create(ui_DebugScreen);
    lv_obj_set_width(ui_StatePanel1, 400);
    lv_obj_set_height(ui_StatePanel1, 70);
    lv_obj_set_x(ui_StatePanel1, 0);
    lv_obj_set_y(ui_StatePanel1, -80);
    lv_obj_set_align(ui_StatePanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_StatePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_StatePanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_StatePanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_StatePanel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_StatePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateLabel1 = lv_label_create(ui_StatePanel1);
    lv_obj_set_width(ui_StateLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StateLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateLabel1, "CAR_OFF");
    lv_obj_set_style_text_font(ui_StateLabel1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownPanel1 = lv_obj_create(ui_DebugScreen);
    lv_obj_set_width(ui_ShutdownPanel1, 400);
    lv_obj_set_height(ui_ShutdownPanel1, 145);
    lv_obj_set_x(ui_ShutdownPanel1, 0);
    lv_obj_set_y(ui_ShutdownPanel1, 40);
    lv_obj_set_align(ui_ShutdownPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ShutdownPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShutdownPanel1, lv_color_hex(0xB39212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShutdownPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ShutdownPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ShutdownPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ShutdownPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShutdownPanel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShutdownPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownLabel1 = lv_label_create(ui_ShutdownPanel1);
    lv_obj_set_width(ui_ShutdownLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShutdownLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownLabel1, "BOTS");
    lv_obj_set_style_text_font(ui_ShutdownLabel1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DebugScreen, ui_event_DebugScreen, LV_EVENT_ALL, NULL);

}
