// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryPercentLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_BatteryPercentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryPercentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryPercentLabel, -180);
    lv_obj_set_y(ui_BatteryPercentLabel, 100);
    lv_obj_set_align(ui_BatteryPercentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryPercentLabel, "100 %");

    ui_BatteryPercentBar = lv_bar_create(ui_HomeScreen);
    lv_bar_set_value(ui_BatteryPercentBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryPercentBar, 40);
    lv_obj_set_height(ui_BatteryPercentBar, 80);
    lv_obj_set_x(ui_BatteryPercentBar, -180);
    lv_obj_set_y(ui_BatteryPercentBar, 47);
    lv_obj_set_align(ui_BatteryPercentBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryPercentBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryPercentBar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryPercentBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryPercentBar, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryPercentBar, lv_color_hex(0x3030F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryPercentBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BatteryTempLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_BatteryTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryTempLabel, -180);
    lv_obj_set_y(ui_BatteryTempLabel, -15);
    lv_obj_set_align(ui_BatteryTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTempLabel, "10 °C");

    ui_BatteryTempBar = lv_bar_create(ui_HomeScreen);
    lv_bar_set_value(ui_BatteryTempBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryTempBar, 40);
    lv_obj_set_height(ui_BatteryTempBar, 80);
    lv_obj_set_x(ui_BatteryTempBar, -180);
    lv_obj_set_y(ui_BatteryTempBar, -70);
    lv_obj_set_align(ui_BatteryTempBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryTempBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryTempBar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryTempBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryTempBar, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryTempBar, lv_color_hex(0x3030F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryTempBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PowerArc = lv_arc_create(ui_HomeScreen);
    lv_obj_set_width(ui_PowerArc, 220);
    lv_obj_set_height(ui_PowerArc, 220);
    lv_obj_set_align(ui_PowerArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_bg_angles(ui_PowerArc, 180, 0);
    lv_obj_set_style_arc_color(ui_PowerArc, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_PowerArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_PowerArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_PowerArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_PowerArc, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_PowerArc, lv_color_hex(0x04E004), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_PowerArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_PowerArc, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_PowerArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_PowerArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RecuArc = lv_arc_create(ui_HomeScreen);
    lv_obj_set_width(ui_RecuArc, 220);
    lv_obj_set_height(ui_RecuArc, 220);
    lv_obj_set_align(ui_RecuArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RecuArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_RecuArc, 5);
    lv_arc_set_bg_angles(ui_RecuArc, 120, 180);
    lv_arc_set_mode(ui_RecuArc, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_RecuArc, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RecuArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RecuArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RecuArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_RecuArc, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RecuArc, lv_color_hex(0xE00404), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RecuArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RecuArc, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RecuArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_RecuArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryArc = lv_arc_create(ui_HomeScreen);
    lv_obj_set_width(ui_BatteryArc, 220);
    lv_obj_set_height(ui_BatteryArc, 220);
    lv_obj_set_align(ui_BatteryArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteryArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_BatteryArc, 50);
    lv_arc_set_bg_angles(ui_BatteryArc, 0, 60);
    lv_arc_set_mode(ui_BatteryArc, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_BatteryArc, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatteryArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatteryArc, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_BatteryArc, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_BatteryArc, lv_color_hex(0x04E004), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatteryArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatteryArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_BatteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, -5);
    lv_obj_set_y(ui_SpeedLabel, -5);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "100");
    lv_obj_set_style_text_font(ui_SpeedLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmhLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_kmhLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmhLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmhLabel, 28);
    lv_obj_set_y(ui_kmhLabel, 18);
    lv_obj_set_align(ui_kmhLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmhLabel, "km/h");

    ui_StatePanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_StatePanel, 100);
    lv_obj_set_height(ui_StatePanel, 30);
    lv_obj_set_x(ui_StatePanel, 180);
    lv_obj_set_y(ui_StatePanel, -60);
    lv_obj_set_align(ui_StatePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_StatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_StatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_StatePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_StatePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_StatePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateLabel = lv_label_create(ui_StatePanel);
    lv_obj_set_width(ui_StateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateLabel, "CAR_OFF");

    ui_ShutdownPanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_ShutdownPanel, 100);
    lv_obj_set_height(ui_ShutdownPanel, 30);
    lv_obj_set_x(ui_ShutdownPanel, 180);
    lv_obj_set_y(ui_ShutdownPanel, -100);
    lv_obj_set_align(ui_ShutdownPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ShutdownPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShutdownPanel, lv_color_hex(0xB39212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShutdownPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ShutdownPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ShutdownPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ShutdownPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ShutdownPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ShutdownPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownLabel = lv_label_create(ui_ShutdownPanel);
    lv_obj_set_width(ui_ShutdownLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShutdownLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownLabel, "BOTS Open");

    ui_BrakeBar = lv_bar_create(ui_HomeScreen);
    lv_bar_set_value(ui_BrakeBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_BrakeBar, 30);
    lv_obj_set_height(ui_BrakeBar, 120);
    lv_obj_set_x(ui_BrakeBar, 160);
    lv_obj_set_y(ui_BrakeBar, 50);
    lv_obj_set_align(ui_BrakeBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrakeBar, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrakeBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrakeBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrakeBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_GasBar = lv_bar_create(ui_HomeScreen);
    lv_bar_set_value(ui_GasBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_GasBar, 30);
    lv_obj_set_height(ui_GasBar, 120);
    lv_obj_set_x(ui_GasBar, 210);
    lv_obj_set_y(ui_GasBar, 50);
    lv_obj_set_align(ui_GasBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_GasBar, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GasBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GasBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GasBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 100);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowermodeLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_PowermodeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowermodeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowermodeLabel, 5);
    lv_obj_set_y(ui_PowermodeLabel, 79);
    lv_obj_set_align(ui_PowermodeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowermodeLabel, "80KW");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);

}
