// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#include "../ui.h"

void ui_LockScreen_screen_init(void)
{
    ui_LockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LockScreen, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LockScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoImage = lv_img_create(ui_LockScreen);
    lv_img_set_src(ui_logoImage, &ui_img_logo_png);
    lv_obj_set_width(ui_logoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_LockScreen, ui_event_LockScreen, LV_EVENT_ALL, NULL);

}
