// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: CarUi

#include "../ui.h"

void ui_MotorScreen_screen_init(void)
{
    ui_MotorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MotorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MotorTempBar = lv_bar_create(ui_MotorScreen);
    lv_bar_set_value(ui_MotorTempBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_MotorTempBar, 60);
    lv_obj_set_height(ui_MotorTempBar, 170);
    lv_obj_set_x(ui_MotorTempBar, -80);
    lv_obj_set_y(ui_MotorTempBar, 10);
    lv_obj_set_align(ui_MotorTempBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MotorTempBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorTempBar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorTempBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MotorTempBar, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorTempBar, lv_color_hex(0x3030F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorTempBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MotorTempLabel = lv_label_create(ui_MotorScreen);
    lv_obj_set_width(ui_MotorTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorTempLabel, -80);
    lv_obj_set_y(ui_MotorTempLabel, -100);
    lv_obj_set_align(ui_MotorTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorTempLabel, "30°C");
    lv_obj_set_style_text_font(ui_MotorTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirTempBar = lv_bar_create(ui_MotorScreen);
    lv_bar_set_value(ui_AirTempBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_AirTempBar, 60);
    lv_obj_set_height(ui_AirTempBar, 170);
    lv_obj_set_x(ui_AirTempBar, -165);
    lv_obj_set_y(ui_AirTempBar, 10);
    lv_obj_set_align(ui_AirTempBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_AirTempBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AirTempBar, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AirTempBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AirTempBar, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AirTempBar, lv_color_hex(0x3030F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AirTempBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_AirTempLabel = lv_label_create(ui_MotorScreen);
    lv_obj_set_width(ui_AirTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirTempLabel, -165);
    lv_obj_set_y(ui_AirTempLabel, -100);
    lv_obj_set_align(ui_AirTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirTempLabel, "30°C");
    lv_obj_set_style_text_font(ui_AirTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kmhLabel1 = lv_label_create(ui_MotorScreen);
    lv_obj_set_width(ui_kmhLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kmhLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmhLabel1, 128);
    lv_obj_set_y(ui_kmhLabel1, 18);
    lv_obj_set_align(ui_kmhLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmhLabel1, "km/h");

    ui_SpeedLabel1 = lv_label_create(ui_MotorScreen);
    lv_obj_set_width(ui_SpeedLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel1, 95);
    lv_obj_set_y(ui_SpeedLabel1, -5);
    lv_obj_set_align(ui_SpeedLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel1, "100");
    lv_obj_set_style_text_font(ui_SpeedLabel1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerArc1 = lv_arc_create(ui_MotorScreen);
    lv_obj_set_width(ui_PowerArc1, 220);
    lv_obj_set_height(ui_PowerArc1, 220);
    lv_obj_set_x(ui_PowerArc1, 100);
    lv_obj_set_y(ui_PowerArc1, 0);
    lv_obj_set_align(ui_PowerArc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerArc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_bg_angles(ui_PowerArc1, 180, 0);
    lv_obj_set_style_arc_color(ui_PowerArc1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_PowerArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_PowerArc1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_PowerArc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_PowerArc1, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_PowerArc1, lv_color_hex(0x04E004), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_PowerArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_PowerArc1, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_PowerArc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_PowerArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RecuArc1 = lv_arc_create(ui_MotorScreen);
    lv_obj_set_width(ui_RecuArc1, 220);
    lv_obj_set_height(ui_RecuArc1, 220);
    lv_obj_set_x(ui_RecuArc1, 100);
    lv_obj_set_y(ui_RecuArc1, 0);
    lv_obj_set_align(ui_RecuArc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RecuArc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_RecuArc1, 5);
    lv_arc_set_bg_angles(ui_RecuArc1, 120, 180);
    lv_arc_set_mode(ui_RecuArc1, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_RecuArc1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RecuArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RecuArc1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RecuArc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_RecuArc1, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RecuArc1, lv_color_hex(0xE00404), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RecuArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RecuArc1, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RecuArc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_RecuArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryArc1 = lv_arc_create(ui_MotorScreen);
    lv_obj_set_width(ui_BatteryArc1, 220);
    lv_obj_set_height(ui_BatteryArc1, 220);
    lv_obj_set_x(ui_BatteryArc1, 100);
    lv_obj_set_y(ui_BatteryArc1, 0);
    lv_obj_set_align(ui_BatteryArc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteryArc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_BatteryArc1, 50);
    lv_arc_set_bg_angles(ui_BatteryArc1, 0, 60);
    lv_arc_set_mode(ui_BatteryArc1, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_BatteryArc1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatteryArc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatteryArc1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryArc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_BatteryArc1, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_BatteryArc1, lv_color_hex(0x04E004), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatteryArc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatteryArc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryArc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_BatteryArc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PowermodeLabel1 = lv_label_create(ui_MotorScreen);
    lv_obj_set_width(ui_PowermodeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowermodeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowermodeLabel1, 100);
    lv_obj_set_y(ui_PowermodeLabel1, 79);
    lv_obj_set_align(ui_PowermodeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowermodeLabel1, "80KW");

    lv_obj_add_event_cb(ui_MotorScreen, ui_event_MotorScreen, LV_EVENT_ALL, NULL);

}
